name = "ws-wnnw"
compatibility_date = "2026-04-22"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "my-cloudflare-backend-v2-db"
database_id = "2955aaee-5e1d-4663-a5ee-d8ea9c5dc018"
migrations_dir = "migrations"
